# Generated by Django 4.1.2 on 2023-02-16 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
        ('accounts', '0001_initial'),
        ('demarcate', '0001_initial'),
        ('video', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('idquestionnaire', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('Subject', models.CharField(blank=True, max_length=250, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('quests', models.IntegerField(blank=True, null=True)),
                ('co_educator', models.ForeignKey(blank=True, db_column='codidusuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('usercode', models.ForeignKey(blank=True, db_column='codtipousuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.usertype')),
            ],
            options={
                'db_table': 'questionnaire',
            },
        ),
        migrations.CreateModel(
            name='questionsWithImages',
            fields=[
                ('idQuestion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('questionImage', models.ImageField(blank=True, null=True, upload_to='question_images/')),
                ('questionDescription', models.CharField(blank=True, max_length=1000, null=True)),
                ('questionOptionA', models.CharField(blank=True, max_length=2, null=True)),
                ('quetionOptionADescription', models.CharField(blank=True, max_length=500, null=True)),
                ('questionOptionB', models.CharField(blank=True, max_length=2, null=True)),
                ('quetionOptionBDescription', models.CharField(blank=True, max_length=500, null=True)),
                ('questionOptionC', models.CharField(blank=True, max_length=2, null=True)),
                ('quetionOptionCDescription', models.CharField(blank=True, max_length=500, null=True)),
                ('questionOptionD', models.CharField(blank=True, max_length=2, null=True)),
                ('quetionOptionDDescription', models.CharField(blank=True, max_length=500, null=True)),
                ('rightAnswerOfQuestion', models.CharField(blank=True, default='A', max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='questionsWithOutImages',
            fields=[
                ('idQuestion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('questionDescription', models.CharField(blank=True, max_length=1000, null=True)),
                ('questionOptionA', models.CharField(blank=True, max_length=2, null=True)),
                ('quetionOptionADescription', models.CharField(blank=True, max_length=500, null=True)),
                ('questionOptionB', models.CharField(blank=True, max_length=2, null=True)),
                ('quetionOptionBDescription', models.CharField(blank=True, max_length=500, null=True)),
                ('questionOptionC', models.CharField(blank=True, max_length=2, null=True)),
                ('quetionOptionCDescription', models.CharField(blank=True, max_length=500, null=True)),
                ('questionOptionD', models.CharField(blank=True, max_length=2, null=True)),
                ('quetionOptionDDescription', models.CharField(blank=True, max_length=500, null=True)),
                ('rightAnswerOfQuestion', models.CharField(blank=True, default='A', max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionTypes',
            fields=[
                ('idtype_questions', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('category', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'question_types',
            },
        ),
        migrations.CreateModel(
            name='SubjectWiseResult',
            fields=[
                ('idResult', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('subjectName', models.CharField(blank=True, max_length=500, null=True)),
                ('marksObtain', models.CharField(default='0', max_length=100)),
                ('studentInfo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('idresult', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('descriptiondate', models.DateTimeField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iduser_user', models.ForeignKey(blank=True, db_column='usuario_idusuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('quiz_quiz_id', models.ForeignKey(blank=True, db_column='questionario_idquestionario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='questions.questionnaire')),
            ],
            options={
                'db_table': 'result',
            },
        ),
        migrations.CreateModel(
            name='QuestionWiseResult',
            fields=[
                ('idQuestionResult', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('marksObtain', models.CharField(default='0', max_length=100)),
                ('questionLink', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='demarcate.demarcatequestion')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('idquestions', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('question', models.IntegerField(blank=True, db_column='questaoNum', null=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('certain', models.CharField(blank=True, default='A', max_length=1, null=True)),
                ('codimage', models.ForeignKey(blank=True, db_column='codimagem', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='images.image', verbose_name='Link Image')),
                ('questionnaireidquestionnaire', models.ForeignKey(blank=True, db_column='questionarioidquestionario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='questions.questionnaire', verbose_name='Related Subject')),
                ('typequestionandidtypequestion', models.ForeignKey(blank=True, db_column='tipoquestoesidtipoquestoes', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='questions.questiontypes', verbose_name='Type of Question')),
                ('videoidvideo', models.ForeignKey(blank=True, db_column='videoidvideo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='video.video', verbose_name='Link Video')),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='CompleteResult',
            fields=[
                ('idCompleteResult', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('totalObtainedMarks', models.CharField(default='0', max_length=100)),
                ('studentInfo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('idcase', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=250, null=True)),
                ('imageidimage', models.ForeignKey(blank=True, db_column='imagemidimagem', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='images.image')),
                ('this_question', models.ForeignKey(db_column='questoesidquestao', on_delete=django.db.models.deletion.DO_NOTHING, to='questions.questions')),
                ('useriduser', models.ForeignKey(blank=True, db_column='usuarioidusuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cases',
            },
        ),
        migrations.CreateModel(
            name='AlternativeQuestions',
            fields=[
                ('idquestions_alternatives', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('letter', models.CharField(blank=True, max_length=1, null=True)),
                ('questoes_questoes_id', models.ForeignKey(db_column='questoes_idquestoes', on_delete=django.db.models.deletion.DO_NOTHING, to='questions.questions', verbose_name='Related Question')),
            ],
            options={
                'db_table': 'alternative_questions',
            },
        ),
    ]
