# Generated by Django 4.1.2 on 2023-02-12 14:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('demarcate', '0004_demarcatequestion_questionmarks'),
        ('questions', '0004_subjectwiseresult_completeresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completeresult',
            name='totalObtainedMarks',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='subjectwiseresult',
            name='marksObtain',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.CreateModel(
            name='QuestionWiseResult',
            fields=[
                ('idQuestionResult', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('marksObtain', models.CharField(default='0', max_length=100)),
                ('questionLink', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='demarcate.demarcatequestion')),
            ],
        ),
    ]
