# Generated by Django 4.1.2 on 2023-02-16 05:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_alter_completeresult_studentinfo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='questionsWithImages',
            fields=[
                ('idQuestion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('questionImage', models.ImageField(blank=True, null=True, upload_to='question_images/')),
                ('questionDescription', models.CharField(blank=True, max_length=1000, null=True)),
                ('questionOptionA', models.CharField(blank=True, max_length=2, null=True)),
                ('quetionOptionADescription', models.CharField(blank=True, max_length=500, null=True)),
                ('questionOptionB', models.CharField(blank=True, max_length=2, null=True)),
                ('quetionOptionBDescription', models.CharField(blank=True, max_length=500, null=True)),
                ('questionOptionC', models.CharField(blank=True, max_length=2, null=True)),
                ('quetionOptionCDescription', models.CharField(blank=True, max_length=500, null=True)),
                ('questionOptionD', models.CharField(blank=True, max_length=2, null=True)),
                ('quetionOptionDDescription', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='questionsWithOutImages',
            fields=[
                ('idQuestion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('questionDescription', models.CharField(blank=True, max_length=1000, null=True)),
                ('questionOptionA', models.CharField(blank=True, max_length=2, null=True)),
                ('quetionOptionADescription', models.CharField(blank=True, max_length=500, null=True)),
                ('questionOptionB', models.CharField(blank=True, max_length=2, null=True)),
                ('quetionOptionBDescription', models.CharField(blank=True, max_length=500, null=True)),
                ('questionOptionC', models.CharField(blank=True, max_length=2, null=True)),
                ('quetionOptionCDescription', models.CharField(blank=True, max_length=500, null=True)),
                ('questionOptionD', models.CharField(blank=True, max_length=2, null=True)),
                ('quetionOptionDDescription', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
