# Generated by Django 4.1.2 on 2023-02-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demarcate', '0003_demarcatequestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='demarcatequestion',
            name='questionMarks',
            field=models.CharField(default='5.0', max_length=100),
        ),
    ]
